name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    if: startsWith(github.event.head_commit.message, '[CI skip]') == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew clean shadowJar

      - name: Select jar
        run: |
          cd build/libs
          echo "FILE=$(ls | grep jar)" >> $GITHUB_ENV

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FILE }}
          path: build/libs/${{ env.FILE }}

      - name: Upload to repo
        run: ./gradlew publish
        env:
          MAVEN_ACCOUNT: '${{ secrets.MAVEN_ACCOUNT }}'
          MAVEN_PASSWORD: '${{ secrets.MAVEN_PASSWORD }}'
